-- insert into restaurant values
--   (default, 'Chipotle', 'mexican', '123 peachtree st');
--
-- insert into restaurant values
--   (default, 'Naan-stop', 'indian', '456 peachtree st' );
--
-- insert into restaurant values
--   (default, 'CraftSteak', 'steak', 'mgm grand, las vegas');
--
--   insert into restaurant values
--     (default, 'Chik-fil-a', 'fast-food', '789 peachtree st');
--
-- insert into reviewer values
-- -- (default, 'siskel', 'siskel@gmail.com', 7);
--
-- insert into review values (default, 1, 4, 35);
--
-- insert into review values (default, 1, 2, 32, 'review chip', 'e-coli +');
--
-- insert into reviewer values
--   (default, 'ebert', 'ebert@heaven.com', 7);
--
-- insert into restaurant values
--   (default, 'Popeyes', 'fast-food', '789 garbage st');
--
--
-- insert into restaurant values
--   (default, 'Outback', 'steak', '789 notaknife drive');
--
--
-- insert into restaurant values
--   (default, 'Cheif running pants''s', 'indian', '1 native st');
--
-- insert into review values
--   (default, 2, 1, 41, 'review outback', 'that''s not a steak');
--
-- insert into review values
--   (default, 2, 2, 40, 'review popeyes', 'tastes like chicken');
